sudo: false

language: node_js

node_js:
  - "5"
  - "6"
  - "7"
  - "node"

install:
  - npm install
  - npm install -g istanbul
  - npm install -g codecov

script:
  - istanbul cover test.js
  - codecov